<?php

defined('SYSPATH') or die('No direct access allowed.');

return array
    (
    'dataset' => array(
        'dir' => APPPATH . 'data/',
        'ext' => 'sqlite',
    ),
    'echonest' => array(
        'api_key' => '4M0DFUG9R81A8U7OB',
        'consumer_key' => '7182fa50a219e737b3fc0f445a38ae76',
        'shared_secret' => 'lpK8ZhjoSSiUfwoBJGzLUQ',
    ),
    'lastfm' => array(
        'api_key' => 'cb4d0e82fd5feaceced5dcd045034065',
        'secret' => '8fae45ccd2d93b336f2ea59ebcf97883',
    ),
    'tags' => array(
        '50s' => array('1950s','50s', '50\'s'),
        '60s' => array('1960s','60s','60\'s'),
        '70s' => array('1970s','70s','70\'s'),
        '80s' => array('1980s','80s','80\'s'),
        '90s' => array('1990s','90s','90\'s'),
        '00s' => array('2000s','00s'),
        'acoustic',
        'alt' => array('alternative','alternative metal','alternative pop','alternative rock'),
        'blues',
        'bluesrock' => array('blues rock','blues-rock'),
        'british',
        'chill' => array('chill','chill out','chilled','chillout'),
        'classic' => array('Classical','classic'),
        'classic rock',
        'club',
        'country',
        'cover' => array('cover','cover song','cover songs','covers'),
        'dance',
        'Disco',
        'drumnbass' => array('Drum and bass','Drum n Bass'),
        'Energetic',
        'electro' => array('electro','electronic','electronica'),
        'funk' => array('funk','funky'),
        'guitar',
        'goth' => array('Gothic','Gothic Metal','Gothic Rock'),
        'hardcore',
        'hiphop' => array('Hip-Hop','hip hop'),
        'House',
        'instrumental',
        'jazz' => array('jazz', 'Smooth Jazz'),
        'latin',
        'live',
        'lounge',
        'metal' => array('metal', 'black metal', 'death metal'),
        'piano',
        'prog' => array('Progressive','Progressive House','Progressive metal','Progressive rock'),
        'rap',
        'reggae',
        'rnb',
        'rock',
        'rnr' => array('Rock and Roll','rock n roll'),
        'singersongwriter' => array('singer songwriter','singer-songwriter'),
        'soundtrack' => array('Soundtrack','Soundtracks'),
        'techno',
        'trance',
    ),
    'ratings' => array(
        'added' => 1,
        'removed' => -1,
        'liked' => 5,
        'disliked' => -5,
        'played' => 1,
    ),
);
